# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95a2f355107e3e05cc0f3fb3d4f85b294c2f69e3436fb0efe9c159056ec44e778dc4d171223414d92965419e5bec8783d3665a0ca0859b996d22262f2a33c85d

test:
  secret_key_base: 31effb8e818d9b2ddb336a68b133185ad2c0e8a312f2d980592f1864bfbbfc939e3029e35e9b6b53170ffc1d27cbd3ea1d81f91d8d9a661616f6c608a98543d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
